/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowsNewRouteImport } from './routes/flows/new'
import { Route as FlowsFlowIdIndexRouteImport } from './routes/flows/$flowId/index'
import { Route as FlowsFlowIdNodesRouteImport } from './routes/flows/$flowId/nodes'
import { Route as FlowsFlowIdEnumerateRouteImport } from './routes/flows/$flowId/enumerate'
import { Route as FlowsFlowIdEditRouteImport } from './routes/flows/$flowId/edit'
import { Route as FlowsFlowIdEdgesRouteImport } from './routes/flows/$flowId/edges'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsNewRoute = FlowsNewRouteImport.update({
  id: '/flows/new',
  path: '/flows/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdIndexRoute = FlowsFlowIdIndexRouteImport.update({
  id: '/flows/$flowId/',
  path: '/flows/$flowId/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdNodesRoute = FlowsFlowIdNodesRouteImport.update({
  id: '/flows/$flowId/nodes',
  path: '/flows/$flowId/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdEnumerateRoute = FlowsFlowIdEnumerateRouteImport.update({
  id: '/flows/$flowId/enumerate',
  path: '/flows/$flowId/enumerate',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdEditRoute = FlowsFlowIdEditRouteImport.update({
  id: '/flows/$flowId/edit',
  path: '/flows/$flowId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdEdgesRoute = FlowsFlowIdEdgesRouteImport.update({
  id: '/flows/$flowId/edges',
  path: '/flows/$flowId/edges',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flows/new': typeof FlowsNewRoute
  '/flows/$flowId/edges': typeof FlowsFlowIdEdgesRoute
  '/flows/$flowId/edit': typeof FlowsFlowIdEditRoute
  '/flows/$flowId/enumerate': typeof FlowsFlowIdEnumerateRoute
  '/flows/$flowId/nodes': typeof FlowsFlowIdNodesRoute
  '/flows/$flowId/': typeof FlowsFlowIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flows/new': typeof FlowsNewRoute
  '/flows/$flowId/edges': typeof FlowsFlowIdEdgesRoute
  '/flows/$flowId/edit': typeof FlowsFlowIdEditRoute
  '/flows/$flowId/enumerate': typeof FlowsFlowIdEnumerateRoute
  '/flows/$flowId/nodes': typeof FlowsFlowIdNodesRoute
  '/flows/$flowId': typeof FlowsFlowIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flows/new': typeof FlowsNewRoute
  '/flows/$flowId/edges': typeof FlowsFlowIdEdgesRoute
  '/flows/$flowId/edit': typeof FlowsFlowIdEditRoute
  '/flows/$flowId/enumerate': typeof FlowsFlowIdEnumerateRoute
  '/flows/$flowId/nodes': typeof FlowsFlowIdNodesRoute
  '/flows/$flowId/': typeof FlowsFlowIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flows/new'
    | '/flows/$flowId/edges'
    | '/flows/$flowId/edit'
    | '/flows/$flowId/enumerate'
    | '/flows/$flowId/nodes'
    | '/flows/$flowId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flows/new'
    | '/flows/$flowId/edges'
    | '/flows/$flowId/edit'
    | '/flows/$flowId/enumerate'
    | '/flows/$flowId/nodes'
    | '/flows/$flowId'
  id:
    | '__root__'
    | '/'
    | '/flows/new'
    | '/flows/$flowId/edges'
    | '/flows/$flowId/edit'
    | '/flows/$flowId/enumerate'
    | '/flows/$flowId/nodes'
    | '/flows/$flowId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlowsNewRoute: typeof FlowsNewRoute
  FlowsFlowIdEdgesRoute: typeof FlowsFlowIdEdgesRoute
  FlowsFlowIdEditRoute: typeof FlowsFlowIdEditRoute
  FlowsFlowIdEnumerateRoute: typeof FlowsFlowIdEnumerateRoute
  FlowsFlowIdNodesRoute: typeof FlowsFlowIdNodesRoute
  FlowsFlowIdIndexRoute: typeof FlowsFlowIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/new': {
      id: '/flows/new'
      path: '/flows/new'
      fullPath: '/flows/new'
      preLoaderRoute: typeof FlowsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId/': {
      id: '/flows/$flowId/'
      path: '/flows/$flowId'
      fullPath: '/flows/$flowId/'
      preLoaderRoute: typeof FlowsFlowIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId/nodes': {
      id: '/flows/$flowId/nodes'
      path: '/flows/$flowId/nodes'
      fullPath: '/flows/$flowId/nodes'
      preLoaderRoute: typeof FlowsFlowIdNodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId/enumerate': {
      id: '/flows/$flowId/enumerate'
      path: '/flows/$flowId/enumerate'
      fullPath: '/flows/$flowId/enumerate'
      preLoaderRoute: typeof FlowsFlowIdEnumerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId/edit': {
      id: '/flows/$flowId/edit'
      path: '/flows/$flowId/edit'
      fullPath: '/flows/$flowId/edit'
      preLoaderRoute: typeof FlowsFlowIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId/edges': {
      id: '/flows/$flowId/edges'
      path: '/flows/$flowId/edges'
      fullPath: '/flows/$flowId/edges'
      preLoaderRoute: typeof FlowsFlowIdEdgesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlowsNewRoute: FlowsNewRoute,
  FlowsFlowIdEdgesRoute: FlowsFlowIdEdgesRoute,
  FlowsFlowIdEditRoute: FlowsFlowIdEditRoute,
  FlowsFlowIdEnumerateRoute: FlowsFlowIdEnumerateRoute,
  FlowsFlowIdNodesRoute: FlowsFlowIdNodesRoute,
  FlowsFlowIdIndexRoute: FlowsFlowIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
